### ISSUE TITLE
Update WP-CLI commands to install translations

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/capistrano-wearerequired#18]
Besides `wp language core` there are now `wp language plugin` and `wp language theme` commands to install translations. Those are available since WP-CLI 2.0.

We should add them as well to make sure we get all the translations for our projects, not just the core ones.

**Comment by grappler** [comment]
@swissspidy I have seen you have started on this. https://github.com/wearerequired/capistrano-wearerequired/tree/wp-cli-language-command

Is there anything missing from doing a PR?

**Comment by swissspidy** [comment]
Just some testing is needed.
