### ISSUE TITLE
Unhelpful error messages when installing languages

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/capistrano-wearerequired#22]
![image 3](https://user-images.githubusercontent.com/841956/45227727-74095100-b2c1-11e8-871a-3e414395029a.png)

**Comment by swissspidy** [comment]
IMO we should just silence the errors here. Knowing that Jetpack isn't available in de_CH isn't really helpful.

**Comment by grappler** [comment]
That is what I was thinking.

**Comment by swissspidy** [comment]
@grappler Can we perhaps revisit this for a possible 1.4.0?

**Comment by grappler** [comment]
As I was working on the translations for Prohelvetia I started to wonder if using `wp plugin list --field=name` to loop through all of the plugins was the best idea.

The reason I started to wonder this is that in Prohelvetia the `languages` folder is symlinked to the shared folder so all of the translations do not need to be installed on every deployment. So running `language install` on every deployment for all of the plugins is not very efficient.

What I realized that the by using the status `uninstalled` we get a list of plugins that have translations available but are not installed. If we used the following command to create a list of plugin slugs we would not encounter the issue with the "language not found" or "already installed".

```
wp @stage language plugin list --all --language=ja --status=uninstalled --field=plugin
```

The only issue is that this command is quite slow and takes quite of bit of time to give an output.

**Comment by swissspidy** [comment]
> The reason I started to wonder this is that in Prohelvetia the `languages` folder is symlinked to the shared folder so all of the translations do not need to be installed on every deployment. So running `language install` on every deployment for all of the plugins is not very efficient.

Why is it that way for that project? Should we reconsider our current approach for all our projects then?

We could use symlinks everywhere, run commands only in the background, etc.

**Comment by grappler** [comment]
> Why is it that way for that project?

I am not sure. I can't remember why.

> Should we reconsider our current approach for all our projects then?

At first I thought downloading the translations on the deployment was the best solution as that way we would get the latest translations but as WP-CLI only loads the translations from the cache the argument does not hold true. Though a `--skip-cache` cache flag would be useful https://github.com/wp-cli/ideas/issues/96

By using symlinks the updating of the translations should be faster. 

> We could use symlinks everywhere, run commands only in the background, etc.

How would you run the commands in the background?

**Comment by swissspidy** [comment]
> At first I thought downloading the translations on the deployment was the best solution as that way we would get the latest translations but as WP-CLI only loads the translations from the cache the argument does not hold true.

For this we also use the update command, not just install. The install command really only needs to be used once (plus every time you add a new plugin to `composer.json`), not with every deployment.

> By using symlinks the updating of the translations should be faster.

Well yeah, ideally things are faster because we only do the install once, then update on subsequent deployments, all while leveraging WP-CLI's caching so there are less downloads.

> How would you run the commands in the background?

Sub shell, cron jobs, etc.
