### ISSUE TITLE
Skip Slack notifications when there's no config for it

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/capistrano-wearerequired#24]
Getting messages like this when not using Slack notifications for a project:

```
  WARN [slackistrano] You are using an outdated configuration that will be removed soon.

  WARN [slackistrano] Please upgrade soon! <https://github.com/phallstrom/slackistrano>

  WARN [slackistrano] Error notifying Slack!

  WARN [slackistrano]   Error: #<SocketError: Failed to open TCP connection to .slack.com:443 (getaddrinfo: nodename nor servname provided, or not known)>
```

If no Slackistrano config is provided, we shouldn't attempt to load and execute it in the first place.

**Comment by grappler** [comment]
This is an issue with https://github.com/phallstrom/slackistrano and not with our code.

Either you could use `set :slackistrano, false` or remove slackistrano completely from the project if you don't need it.

What is the use case here?

**Comment by swissspidy** [comment]
Perhaps we could set it to false by default then?

I‘m using this Gem for a private project where I don‘t need Slack notifications.

I can‘t really remove Slackistrano there because it‘s a direct dependency of this Gem.

**Comment by grappler** [comment]
Maybe something like this would work. I am not sure where to place `set_if_empty :slackistrano, false`

```ruby
namespace :slackistrano do
  task :defaults do
    set_if_empty :slackistrano, false
  end
  before 'slack:deploy', 'slackistrano:defaults'
end
```
